# Generated by Django 5.2.4 on 2025-08-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskModel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
